### ISSUE TITLE
[Bot/Bug]: Bot no more useable since last update / Connection lost on 90% of bots

### ISSUE THREAD

**Issue by Hausi1980** [MinecraftBot-com/MineBot-V3-Issues#68]
### Current Behavior

All my accounts are disconnecting nearly every 5 minutes. 
This is crazy.
Together with #67 it is nor useable. Please give some eta about it. 

### Steps To Reproduce

Server is: blockbande.de

### Screenshots

![image](https://github.com/user-attachments/assets/04a8235a-a36b-4edd-aa38-7c2c7c90e1d0)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by Hausi1980** [comment]
![image](https://github.com/user-attachments/assets/60ba9f8a-c6b3-4465-bcf5-4b858d053f75)

**Comment by OnlyQubes** [comment]
It has been identified that the issue is caused by unstable proxies that we are using. We are talking to our proxy provider to see if there is anything that can be done without changing proxy providers.

For now, will be adding a few options for more stable connections that we can provide, those being: data center proxies, and native server ip address. These should be used for the most stable connection, but were not included initially as anti-vpn plugins may detect this. You should see an option for this tomorrow (11/09/2024 23:00 GMT)

Additionally we will be carrying out tests to see what other residential proxy providers we can find and reliably use.

**Comment by OnlyQubes** [comment]
Hi,

I sincerely apologize for the inconvenience and for the delays we’ve encountered. We understand the frustration this may have caused.

The good news is that we have completely reworked the networking setup, which should now result in significantly more stable connections and improved ping. In addition, the update allows you to select your preferred IP type, offering more control over the connection's properties.

For further details, you can read about the different non-proxy connection types here: [Non-Proxied Connection Settings](https://help.minecraftbot.com/settings/connection-settings#non-proxied-connection-settings).

Thank you for your patience and understanding.
